version: "3.9"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/var/www/html
        ports:
            - "8000:80"
        depends_on:
            - redis
            - db
            - db_testing
        expose:
            -   "9000"

    redis:
        image: redis:7
        ports:
            - "6379:6379"

    db:
        image: postgres:15
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "5432:5432"

    db_testing:
        image: postgres:15
        environment:
            POSTGRES_USER: ${TEST_DB_USERNAME}
            POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
            POSTGRES_DB: ${TEST_DB_DATABASE}
        ports:
            - "5433:5432"

    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
                - app
